      SUBROUTINE OFPPNT (OUT,NWDS,FMT)
C
      LOGICAL         DEBUG
      INTEGER         OUT(NWDS), FMT(300)
      COMMON /SYSTEM/ SYSBUF,    L
      DATA    DEBUG / .FALSE. /
C
      IF (DEBUG) WRITE (L,10) (FMT(K),K=1,32)
 10   FORMAT (' FMT=',32A4)
C     WRITE (L,FMT,IOSTAT=IOSXX) (OUT(K),K=1,NWDS)
      CALL FORWRT (FMT, OUT, OUT, OUT, OUT, NWDS)
      RETURN
      END
