      SUBROUTINE ERRTRC (NAME,NO)        
C
C     THIS SUBROUTINE INTENTIONALLY MAKES A FATAL ERROR, AND FORCE THE
C     SYSTEM TO GO THRU AN ERROR TRACEBACK        
C        
      CHARACTER*8      NAME
      COMMON /SYSTEM / IBUF,NOUT,NOGO,IN
      COMMON /BLANK  / IZ(1)
C
      WRITE  (NOUT,10) NAME,NO
   10 FORMAT ('0*** ERROR TRACEBACK INITIATED BY ',A8,' AT',I5)
      JX = 100000000 + IBUF - NOUT
      IZ(JX) = JX
      JX = -JX
      X  = JX
      X  = SQRT(X)
      WRITE (JX) X
      RETURN
      END
